In [44]:
import warnings
warnings.filterwarnings("ignore")

In [45]:
from sklearn.datasets import  make_classification
from sklearn.linear_model import LogisticRegression
X,y = make_classification(n_samples=1000,n_features=10,n_informative=5,n_redundant=5,n_classes=2,random_state=1)

In [46]:
X, y

(array([[ 2.56999479, -0.13019997,  3.16075093, ..., -1.93094078,
          3.26130366,  2.05692145],
        [ 0.34129317,  2.51321418, -0.80416572, ...,  6.24734437,
         -1.92769365,  2.9503149 ],
        [ 2.27539972,  3.36561455,  0.17164362, ...,  2.74693781,
          0.13492444,  2.00339547],
        ...,
        [ 0.5234359 ,  1.90466429,  0.93243365, ...,  1.53945231,
          1.90646166,  1.99458587],
        [ 1.33747921,  3.25859684,  0.78792366, ...,  5.18788314,
         -0.82071083,  3.51411431],
        [-0.98534299,  0.83919047,  2.5820803 , ...,  3.04705685,
          0.66885641,  3.32838496]]),
 array([1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
        1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
   

In [69]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [70]:
# GridSearchCV >> take all possible combination 

In [71]:
from sklearn.model_selection import GridSearchCV
params = {'penalty':('l1','l2','elasticnet'), 'C':[1,2,3,4,5,10,20,30,40]}
classifier =LogisticRegression()

In [72]:
classifier

LogisticRegression()

In [73]:
clf = GridSearchCV(classifier,param_grid=params,cv=5,verbose=3)

In [74]:
clf

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5, 10, 20, 30, 40],
                         'penalty': ('l1', 'l2', 'elasticnet')},
             verbose=3)

In [75]:
clf.fit(X_train,y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV 1/5] END .....................C=1, penalty=l1;, score=nan total time=   0.0s
[CV 2/5] END .....................C=1, penalty=l1;, score=nan total time=   0.0s
[CV 3/5] END .....................C=1, penalty=l1;, score=nan total time=   0.0s
[CV 4/5] END .....................C=1, penalty=l1;, score=nan total time=   0.0s
[CV 5/5] END .....................C=1, penalty=l1;, score=nan total time=   0.0s
[CV 1/5] END ...................C=1, penalty=l2;, score=0.856 total time=   0.0s
[CV 2/5] END ...................C=1, penalty=l2;, score=0.762 total time=   0.0s
[CV 3/5] END ...................C=1, penalty=l2;, score=0.806 total time=   0.0s
[CV 4/5] END ...................C=1, penalty=l2;, score=0.806 total time=   0.0s
[CV 5/5] END ...................C=1, penalty=l2;, score=0.800 total time=   0.0s
[CV 1/5] END .............C=1, penalty=elasticnet;, score=nan total time=   0.0s
[CV 2/5] END .............C=1, penalty=elasticn

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5, 10, 20, 30, 40],
                         'penalty': ('l1', 'l2', 'elasticnet')},
             verbose=3)

In [76]:
clf.best_score_

0.80625

In [77]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [78]:
model=LogisticRegression(C=1,penalty='l2')

In [79]:
model.fit(X_train,y_train)

LogisticRegression(C=1)

In [81]:
y_pred = model.predict(X_test)

In [82]:
y_pred 

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1])

In [83]:
from sklearn.metrics import confusion_matrix, accuracy_score , classification_report

In [84]:
print(confusion_matrix(y_test,y_pred))
print("your accuracy score is",accuracy_score(y_test,y_pred))

print(classification_report(y_test,y_pred))

[[84 10]
 [25 81]]
your accuracy score is 0.825
              precision    recall  f1-score   support

           0       0.77      0.89      0.83        94
           1       0.89      0.76      0.82       106

    accuracy                           0.82       200
   macro avg       0.83      0.83      0.82       200
weighted avg       0.83      0.82      0.82       200



In [85]:
# randomized searchcv


In [102]:
from sklearn.model_selection import RandomizedSearchCV
clf=RandomizedSearchCV(classifier,param_distributions=params,cv=5,n_iter=10,verbose=4)
clf.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END ...................C=4, penalty=l2;, score=0.856 total time=   0.0s
[CV 2/5] END ...................C=4, penalty=l2;, score=0.762 total time=   0.0s
[CV 3/5] END ...................C=4, penalty=l2;, score=0.806 total time=   0.0s
[CV 4/5] END ...................C=4, penalty=l2;, score=0.806 total time=   0.0s
[CV 5/5] END ...................C=4, penalty=l2;, score=0.800 total time=   0.0s
[CV 1/5] END .....................C=4, penalty=l1;, score=nan total time=   0.0s
[CV 2/5] END .....................C=4, penalty=l1;, score=nan total time=   0.0s
[CV 3/5] END .....................C=4, penalty=l1;, score=nan total time=   0.0s
[CV 4/5] END .....................C=4, penalty=l1;, score=nan total time=   0.0s
[CV 5/5] END .....................C=4, penalty=l1;, score=nan total time=   0.0s
[CV 1/5] END .............C=3, penalty=elasticnet;, score=nan total time=   0.0s
[CV 2/5] END .............C=3, penalty=elasticne

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 2, 3, 4, 5, 10, 20, 30, 40],
                                        'penalty': ('l1', 'l2', 'elasticnet')},
                   verbose=4)

In [103]:
clf.best_score_

0.80625

In [104]:
clf.best_params_

{'penalty': 'l2', 'C': 4}