In [15]:
from sklearn.datasets import make_classification  # this is use for  just making  dataset
from  sklearn.model_selection import train_test_split

X,y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=1)


In [16]:
X

array([[-2.04582165, -0.13791624, -0.08071423, ...,  2.48194524,
         0.74236675,  0.23154789],
       [-0.98726024,  1.30120189,  2.37734888, ...,  0.55445754,
        -0.21892143, -0.37608578],
       [ 0.57335921,  0.09375582,  0.4662521 , ..., -0.6088508 ,
         0.79903499, -0.17121177],
       ...,
       [-0.70737159,  1.07650943,  0.58510456, ..., -1.51337602,
         0.90239871, -0.69230951],
       [-0.20706849,  1.17319848, -1.94478665, ..., -0.32820676,
         1.5711921 ,  1.14877729],
       [-2.16769231, -2.54871672,  2.89359255, ...,  0.71535366,
         0.34329241,  1.07350284]])

In [22]:
y.shape

(1000,)

In [18]:
X_train , X_test , y_train , y_test = train_test_split(X ,y, test_size=0.2,random_state=1)

In [19]:
X_train

array([[-0.64628725,  2.56641658, -0.59358153, ...,  0.90827206,
        -1.71695976, -0.38555497],
       [-1.50444431,  0.39575313, -0.83153588, ...,  2.47800544,
         1.29962918, -0.59207261],
       [-0.39151879, -0.09869076,  1.32459307, ...,  0.66345104,
         0.35720182, -0.98291706],
       ...,
       [-0.00383186,  0.09203615, -0.70121505, ..., -2.16249308,
        -0.33068834,  0.07266646],
       [ 2.45888615, -0.35941149,  0.02597242, ..., -0.056518  ,
        -0.59516384, -0.51703825],
       [ 1.84222699, -0.46434485, -0.05381296, ...,  0.80643863,
         0.40912571, -0.19642545]])

In [20]:
y_train

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,

In [23]:
X_train.shape,X_test.shape

((800, 20), (200, 20))

In [24]:
y_train.shape,y_test.shape

((800,), (200,))

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

In [26]:
# now we are going to build this all 4 model 

In [28]:
lr_clf = LogisticRegression()
svm_clf = SVC()
dt_clf = DecisionTreeClassifier()
nb_clf = GaussianNB()

In [29]:
# now next thing that i am going to say you >> 

In [31]:
from sklearn.ensemble import VotingClassifier 
# what is meaning of this?
# >> so meaning of this is >> this voting classifier -- if you see
# estimators >> gives the estimators what ever number of models that you want to give it  as many number of  model you want c
# voting = hard and soft  
# In classification either you model give s that "prediction" or give "Probability" 
# so if you use hard that is default that it give you "predicated class labels " or use soft >> it will you probability 


In [32]:
# I am goint use this VotingClassifier  here 
#  In this VotingClassifier  what I am go to do ?
# I am going to use estimators=" "
# estimators=" " << and here now  I will pass list[] and inside this list i will put all the models >> so you have 4 model
# Now How i will put this 4 model >> see it 
# Let say 1st one is Logistic regression so it name is >> you name it what ever you want as like "log_regression " and  gives the empty object like " lr_clf()" and similar to all 3 mode 

ensebles_clf = VotingClassifier(estimators=[('logistic regression',lr_clf) , ('support vector classifier',svm_clf) , ('decision tree classifier',dt_clf) , ('Gaussian NB',nb_clf) ])

In [34]:
ensebles_clf

VotingClassifier(estimators=[('logistic regression', LogisticRegression()),
                             ('support vector classifier', SVC()),
                             ('decision tree classifier',
                              DecisionTreeClassifier()),
                             ('Gaussian NB', GaussianNB())])

In [35]:
# now you have to family of algorithms  and now what have to do


In [36]:
ensebles_clf.fit(X_train,y_train)

VotingClassifier(estimators=[('logistic regression', LogisticRegression()),
                             ('support vector classifier', SVC()),
                             ('decision tree classifier',
                              DecisionTreeClassifier()),
                             ('Gaussian NB', GaussianNB())])

In [37]:
# model is trains with all of models >> then >>  you can have >> let see

In [38]:
y_pred = ensebles_clf.predict(X_test)

In [39]:
y_pred

array([0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1])

In [40]:
# now you can have this evalation metrix 

In [48]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.87

In [49]:
print(f"Accuracy of model {accuracy_score(y_test, y_pred)*100:.2f}%")

Accuracy of model 87.00%


This is How you build the model. And in the backend -  it will train all the model And give you the prediction .

So this the way you will make " Custom ensambles model"



------------------------------------------------------------------------------
so Here In this case prediction has be made by each of the algorithms.

And By Voting classification  final prediction will taken and from final prediction this accuracy will come.

------------------------------ VotingClassifier ------------------------------------------------------------------------------------------
The VotingClassifier in scikit-learn is an ensemble learning method that combines multiple machine learning models (classifiers) to improve overall performance. It aggregates the predictions from individual models and makes the final prediction based on voting.


Here’s a step-wise explanation of the VotingClassifier :

1. Understanding the Voting Classifier

	•	The VotingClassifier is an ensemble method that combines the predictions of multiple classifiers (models).
	•	It uses the predictions of each individual classifier to make a final decision through a voting mechanism.

2. Individual Classifiers

	•	First, select and train multiple models (classifiers) independently. These can be different algorithms like Logistic Regression, Decision Trees, Support Vector Machines, etc.
	•	These models make individual predictions on the dataset.

3. Types of Voting

	•	Voting refers to how the final prediction is made by the ensemble:
	•	Hard Voting: Each classifier makes a prediction, and the final prediction is the majority vote (i.e., the class label that appears most often across models).
	•	Soft Voting: Each classifier predicts class probabilities, and the final prediction is based on the average of these probabilities. The class with the highest average probability is selected.

4. Combining the Classifiers

	•	After individual classifiers are selected, they are combined into a VotingClassifier.
	•	You must specify whether you want hard voting (majority vote) or soft voting (probability averaging).

5. Training the VotingClassifier

	•	Once the individual classifiers are combined, the VotingClassifier is trained on the dataset.
	•	This step is similar to training a single model, but the VotingClassifier learns how to combine predictions from multiple models.

6. Making Predictions

	•	After the ensemble is trained, it makes predictions by either taking the majority class (in hard voting) or by averaging probabilities (in soft voting).

7. Advantages of Voting

	•	Voting often leads to better generalization because it reduces the variance and bias of individual models.
	•	Combining weak or strong models together in this way can lead to improved accuracy and performance.

In summary, voting in the VotingClassifier is a method for deciding the final outcome by either majority voting (hard) or averaging predicted probabilities (soft). This helps to combine the strengths of multiple classifiers.

---------------------------------------------------------------------------------------------------------------------------------
Let Say 

M1 ----> Predicted -> 1 

M2 ----> Predicted -> 1

M3 ----> Predicted -> 0

M4 ----> Predicted -> 0

So In this case What will Voting Classifier is selected. 

This  is the One question .

So >>  In this cases >> Generally you will not incounter this because alway 
If it is binary class problems so alway build odd number of model 
But even you se no I want only even number of binary class problem 
then Voting classifie select randomly either 1 or 0

But Idea is when ever such case happen for binary classification you always make odd number of then only one class will selected that is 0th class