In [1]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

X,y = make_regression(n_samples=1000, n_features=10, noise=0.1, random_state=1)

In [2]:
X

array([[-1.24634541, -2.3575232 ,  0.60972409, ..., -1.25935848,
        -0.11048061,  0.46983129],
       [-0.68085157, -1.06787658,  0.57296273, ..., -0.01781755,
         0.45794708, -0.6001388 ],
       [-0.14894123,  1.16533544, -0.63259014, ...,  1.89716069,
        -0.20984695, -1.38139115],
       ...,
       [ 1.32960903, -1.08278525,  0.44347873, ..., -0.48363166,
         0.01880501,  0.56264832],
       [ 1.03703898,  0.67261975,  1.00568668, ...,  0.61472628,
         0.35356722, -0.34898419],
       [ 0.438562  ,  0.92781985,  0.72667997, ..., -1.09330391,
        -0.37195994,  0.22445073]])

In [3]:
y

array([-1.29703788e+02, -1.80999622e+01, -2.48373532e+02, -5.47790773e+01,
        2.53389312e+01,  1.64353500e+01, -1.62379961e+02,  8.68801965e+01,
       -3.03384035e+01, -1.99726617e+02, -1.13506241e+02, -1.90063912e+02,
       -1.87538897e+02,  1.72228819e+02,  6.16386076e+01, -3.56835616e+02,
        8.24251916e+01,  1.61358017e+02,  1.52957393e+02,  5.00424227e+02,
        1.21062317e+02,  4.95831180e+01, -1.77278355e+02, -2.49458193e+01,
       -1.65450348e+02,  4.18445290e+01, -6.76893860e+01, -6.46220878e+01,
       -1.11488894e+02,  2.30651763e+02,  2.56645774e+02, -1.84174552e+02,
        2.98886683e+02, -2.73732404e+01,  4.17040920e+02,  1.01523419e+02,
       -1.23009941e+02,  3.56833517e+02, -1.71822143e+02,  3.61894176e+02,
        1.97745189e+02, -1.85490215e+02,  1.36198413e+02, -3.26485048e+02,
       -1.14069731e+02,  4.77747550e+01,  1.62640400e+02,  9.41057983e+01,
       -4.16816637e+01, -5.20442942e+01,  3.44121608e+02,  1.04900656e+02,
       -2.01206138e+02, -

In [4]:
X_train , X_test , y_train , y_test = train_test_split(X ,y, test_size=0.2,random_state=1)

In [5]:
X_train.shape,X_test.shape

((800, 10), (200, 10))

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [8]:
lr = LinearRegression()
dtr = DecisionTreeRegressor()
svr = SVR(kernel="linear")

In [13]:
from sklearn.ensemble import VotingRegressor
ensemble_regression  =VotingRegressor(estimators=[("Multiple Linear Regression",lr) , ("DecisionTreeRegressor",dtr) , ("Support Vector Regression ",svr)])

In [14]:
ensemble_regression

VotingRegressor(estimators=[('Multiple Linear Regression', LinearRegression()),
                            ('DecisionTreeRegressor', DecisionTreeRegressor()),
                            ('Support Vector Regression ',
                             SVR(kernel='linear'))])

In [15]:
ensemble_regression.fit(X_train,y_train)

VotingRegressor(estimators=[('Multiple Linear Regression', LinearRegression()),
                            ('DecisionTreeRegressor', DecisionTreeRegressor()),
                            ('Support Vector Regression ',
                             SVR(kernel='linear'))])

In [21]:
 ensemble_regression.predict(X_test)

array([  59.91158544,   40.84457857, -165.4724235 ,  -62.03447258,
        504.50112016,  313.0284345 ,   46.31822525,  -54.52450392,
        -94.8648865 ,  -70.50882469, -101.56014412,   11.88158399,
        -50.14067936, -143.26542553, -311.55125961, -145.45365535,
       -288.00715565, -163.33857005,  -29.35579152, -187.5724345 ,
        -44.38230655, -136.20598004,  302.11514742, -204.54359021,
          4.43576336,  191.73203423,  237.17596557,   58.05584608,
        -66.68161414,  109.32205511,   20.05618562,  245.5369679 ,
        133.77866601,  273.59571139,  123.2212309 ,  103.05992915,
         62.79038637, -384.31221047, -184.14777544,  -83.05983246,
         -6.88778754,  -99.16742966,   62.48655026, -129.89131047,
         82.36148825,    6.14477113,  182.64152303, -124.26323706,
        162.76042005, -300.48967015,  225.48351948,  364.42615339,
       -229.08421669,   77.88087229,  -41.05039087,  101.2045309 ,
        184.32945339,   70.6830957 ,   39.56063747,   91.97986

In [22]:
# Now guys It was just introduction , It was just basic Custom ensebles 

# But In Industry >> You don't do  this ways

# how will do that so see the next code In file number >>>>29



