In [57]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns 

import warnings
warnings.filterwarnings("ignore")

In [58]:
# now i am goin to load the dataset
df=sns.load_dataset("tips")

In [59]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [60]:
# since it is a classification problem so what can I am going to do
# >> I cam make a target variable .>> may be I used time as target variable and you want to predict it

In [61]:
df.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [62]:
# if you see here 'Dinner', 'Lunch' >> so what can i do let see
# I can simple covert this in number amd then it as target variable 

In [63]:
# now what you want to automate

# 1 encoding
# 2 Scaling 
# 3 missing value treatment 

# this is what we are going to see in pipeline

In [64]:
# now >> time is their >> time is nominal or ordinal variable >> what is think you
# is their is any order --> no 
# it is nominal 
# so  for nominal we you the >>  jusrt do the level encoding 

In [65]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['time']= encoder.fit_transform(df["time"]) # now if you see df[time] is coverted to numerical value
df

total_bill   tip     sex smoker   day  time  size
0         16.99  1.01  Female     No   Sun     0     2
1         10.34  1.66    Male     No   Sun     0     3
2         21.01  3.50    Male     No   Sun     0     3
3         23.68  3.31    Male     No   Sun     0     2
4         24.59  3.61  Female     No   Sun     0     4
..          ...   ...     ...    ...   ...   ...   ...
239       29.03  5.92    Male     No   Sat     0     3
240       27.18  2.00  Female    Yes   Sat     0     2
241       22.67  2.00    Male    Yes   Sat     0     2
242       17.82  1.75    Male     No   Sat     0     2
243       18.78  3.00  Female     No  Thur     0     2

[244 rows x 7 columns]

In [66]:
df.time.unique() # dinner is 0 and lunch is 1

array([0, 1])

In [67]:
# aim  is >> to predict time 

In [68]:
# now >> what to do next 

In [69]:
# first i wll divide the data into x y

In [70]:
X=df.drop('time',axis=1)
y=df['time']

In [71]:
X

total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
1         10.34  1.66    Male     No   Sun     3
2         21.01  3.50    Male     No   Sun     3
3         23.68  3.31    Male     No   Sun     2
4         24.59  3.61  Female     No   Sun     4
..          ...   ...     ...    ...   ...   ...
239       29.03  5.92    Male     No   Sat     3
240       27.18  2.00  Female    Yes   Sat     2
241       22.67  2.00    Male    Yes   Sat     2
242       17.82  1.75    Male     No   Sat     2
243       18.78  3.00  Female     No  Thur     2

[244 rows x 6 columns]

In [72]:
y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: time, Length: 244, dtype: int64

In [73]:
# next step is train test split

In [74]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train ,y_test = train_test_split(X,y,test_size=0.20,random_state=1)

In [75]:
X_train

total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
154       19.77  2.00    Male     No   Sun     4
167       31.71  4.50    Male     No   Sun     4
110       14.00  3.00    Male     No   Sat     2
225       16.27  2.50  Female    Yes   Fri     2
..          ...   ...     ...    ...   ...   ...
137       14.15  2.00  Female     No  Thur     2
72        26.86  3.14  Female    Yes   Sat     2
140       17.47  3.50  Female     No  Thur     2
235       10.07  1.25    Male     No   Sat     2
37        16.93  3.07  Female     No   Sat     3

[195 rows x 6 columns]

In [76]:
X_test

total_bill    tip     sex smoker   day  size
67         3.07   1.00  Female    Yes   Sat     1
243       18.78   3.00  Female     No  Thur     2
206       26.59   3.41    Male    Yes   Sat     3
122       14.26   2.50    Male     No  Thur     2
89        21.16   3.00    Male     No  Thur     2
218        7.74   1.44    Male    Yes   Sat     2
58        11.24   1.76    Male    Yes   Sat     2
186       20.90   3.50  Female    Yes   Sun     3
177       14.48   2.00    Male    Yes   Sun     2
4         24.59   3.61  Female     No   Sun     4
220       12.16   2.20    Male    Yes   Fri     2
226       10.09   2.00  Female    Yes   Fri     2
116       29.93   5.07    Male     No   Sun     4
107       25.21   4.29    Male    Yes   Sat     2
170       50.81  10.00    Male    Yes   Sat     3
241       22.67   2.00    Male    Yes   Sat     2
181       23.33   5.65    Male    Yes   Sun     2
51        10.29   2.60  Female     No   Sun     2
27        12.69   2.00    Male     No   Sat     2
240       27.18   2.00  Female    Yes   Sat     2
219       30.14   3.09  Female    Yes   Sat     4
34        17.78   3.27    Male     No   Sat     2
93        16.32   4.30  Female    Yes   Fri     2
183       23.17   6.50    Male    Yes   Sun     4
118       12.43   1.80  Female     No  Thur     2
117       10.65   1.50  Female     No  Thur     2
106       20.49   4.06    Male    Yes   Sat     2
73        25.28   5.00  Female    Yes   Sat     2
38        18.69   2.31    Male     No   Sat     3
210       30.06   2.00    Male    Yes   Sat     3
202       13.00   2.00  Female    Yes  Thur     2
44        30.40   5.60    Male     No   Sun     4
62        11.02   1.98    Male    Yes   Sat     2
238       35.83   4.67  Female     No   Sat     3
85        34.83   5.17  Female     No  Thur     4
224       13.42   1.58    Male    Yes   Fri     2
39        31.27   5.00    Male     No   Sat     3
31        18.35   2.50    Male     No   Sat     4
18        16.97   3.50  Female     No   Sun     3
132       11.17   1.50  Female     No  Thur     2
119       24.08   2.92  Female     No  Thur     4
19        20.65   3.35    Male     No   Sat     3
91        22.49   3.50    Male     No   Fri     2
69        15.01   2.09    Male    Yes   Sat     2
33        20.69   2.45  Female     No   Sat     4
90        28.97   3.00    Male    Yes   Fri     2
35        24.06   3.60    Male     No   Sat     3
11        35.26   5.00  Female     No   Sun     4
29        19.65   3.00  Female     No   Sat     2

In [77]:
# first of all what ever pre - processing steps that you will be doing in train data 
# don’t you think you that same pre -  processing steps should be done in  the test data
# yes or no >>>>>>> tell me

# yes

# what ever you are doing pre - processing steps  in train data the same pre  processing 
# steps should be done in test data 

# then only you get the correct prediction 


In [78]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [79]:
# handling missing value
# data encoding
# feature scaling

In [80]:
# Now guys lets make a pipeline which will do this there three things sequentially 

In [81]:
# How to do that

In [82]:
# fist of all handing missing values >> impuation

from sklearn.impute import SimpleImputer # for missing value
from sklearn.preprocessing import OneHotEncoder # for data encoding
from sklearn.preprocessing import StandardScaler # for feature scaling


# pipeline >> pipeline is a sequence of data transformation 
# column transformer  >> this is groups all the pipelines steps for each of the columns

# now how to import pipeline
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
# Importing Pipeline from sklearn to create a sequential model workflow
# Importing ColumnTransformer to apply different preprocessing steps to specific columns of a dataset

In [83]:
cat_cols = ['sex','smoker','day']
num_cols = ['total_bill','tip','size']

In [84]:
# feature engineering automation using pipeline and columns transformer

#Fist of all how to make pipeline.

num_pipeline = Pipeline(steps=[('imputation',SimpleImputer(strategy="median")),
                               ('scaling',StandardScaler())])

cat_pipeline = Pipeline(steps=[('imputation',SimpleImputer(strategy="most_frequent")),
                               ('encoding',OneHotEncoder() )])

In [85]:
# now you will use columns transformer to have this pipeline ready

In [86]:
preprocessor = ColumnTransformer([('numeral Pipeline',num_pipeline,num_cols),
                  ('Categorical Pipeline',cat_pipeline,cat_cols )])

In [87]:
preprocessor

ColumnTransformer(transformers=[('numeral Pipeline',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['total_bill', 'tip', 'size']),
                                ('Categorical Pipeline',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OneHotEncoder())]),
                                 ['sex', 'smoker', 'day'])])

In [88]:
# Again what you will do now 
# first things >> you will aways do fit_transform on your train data and already you know you want to put transform in your test data  

X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)
# now your data is ready 

In [90]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression


models = {"SVC": SVC(),
         "DTC":DecisionTreeClassifier(),
         "Log Regression":LogisticRegression(),
         "rf":RandomForestClassifier()
         }


In [91]:
from sklearn.metrics import accuracy_score

def model_train_eval(X_train,y_train,X_test, y_test,models):
    evaluation = {}
    for i in range(len(models)):
        model = list(models.values())[i]
        model.fit(X_train,y_train)
        y_pred = model.predict(X_test)
        model_score = accuracy_score(y_test,y_pred)
        evaluation[list(models.keys())[i]] = model_score
    return evaluation


In [94]:
model_train_eval(X_train,y_train, X_test, y_test,models)

{'SVC': 0.9183673469387755,
 'DTC': 0.9183673469387755,
 'Log Regression': 0.9183673469387755,
 'rf': 0.8979591836734694}

In [95]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [96]:
rf

RandomForestClassifier()

In [97]:
rf.fit(X_train, y_train)

RandomForestClassifier()

In [98]:
y_pred= rf.predict(X_test)

In [99]:
y_pred

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0])

In [100]:
accuracy_score(y_test , y_pred)

0.8979591836734694

In [101]:
# hyper parameter 

In [102]:
from sklearn.model_selection import GridSearchCV

params = {
    'max_depth': [1,2,3,4,10,20,30],
    'n_estimators' :[50,100,200,300,400,1000],
    'criterion': ['gini', 'entropy']
}

In [103]:
params

{'max_depth': [1, 2, 3, 4, 10, 20, 30],
 'n_estimators': [50, 100, 200, 300, 400, 1000],
 'criterion': ['gini', 'entropy']}

In [104]:
clf = GridSearchCV(rf,param_grid=params,cv=5 ,scoring="accuracy",verbose=3)

In [105]:
clf

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 10, 20, 30],
                         'n_estimators': [50, 100, 200, 300, 400, 1000]},
             scoring='accuracy', verbose=3)

In [106]:
clf.fit(X_train,y_train)

Fitting 5 folds for each of 84 candidates, totalling 420 fits
[CV 1/5] END criterion=gini, max_depth=1, n_estimators=50;, score=0.923 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=1, n_estimators=50;, score=0.974 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=1, n_estimators=50;, score=1.000 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=1, n_estimators=50;, score=0.949 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=1, n_estimators=50;, score=0.821 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.923 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.974 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.949 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=1, n_estimators=100;, score=1.000 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=1, n_estimators=100;, score=0.769 total time=   0.0s
[CV 1/5] END criterion=

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 10, 20, 30],
                         'n_estimators': [50, 100, 200, 300, 400, 1000]},
             scoring='accuracy', verbose=3)

In [107]:
clf.predict(X_test)

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0])

In [108]:
clf.best_params_

{'criterion': 'gini', 'max_depth': 1, 'n_estimators': 400}

In [109]:
clf.best_score_

0.9794871794871796