In [60]:
# Nominal| OHE encoding  >> so you create binary vector its means  0 and 1 for each category
# and create dummy variable 

In [61]:
import numpy as np
import pandas as pd

# to create dummy varible which are helped by sklearn
from sklearn.preprocessing import OneHotEncoder # this "oneHotEncoder" will be actually helping to create the dummy variable 


import warnings
warnings.filterwarnings("ignore")

In [62]:
df=pd.DataFrame({'status':['Single','Married','Single','Relationship','Married','Single']})

In [63]:
df

status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [64]:
# first ask to  your self and this data is ordinal or nominal >>means >> understand the data >>
# it is nominal 
# so what to do now >> let see >> then we make the dummy variable using>>  OneHotEnder()
# and now onwards many time you see you will initialise the  object of
# what ever process that can you do  se here in this case you initialise of object of 
# OneHotEnder


In [65]:
encoder = OneHotEncoder()
encoder

OneHotEncoder()

In [66]:
# It is instant of OneHotEncoder 


In [67]:
encoder.fit(df[['status']]) # now fit Known who one single who one married like that

OneHotEncoder()

In [68]:
encoder.transform(df[['status']])

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [69]:
encoder.transform(df[['status']]).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [70]:
encoded = encoder.fit_transform(df[['status']]).toarray() # here directly 

In [71]:
encoded
# Now dummy variable created . 

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [72]:
# and this matrix is called sparse matrix 

In [73]:
# but still you are not aware is which feature are what 
# that also this particular "encoder" object give to you
# you can use encoder.get_feature_names_out

In [74]:
encoder.get_feature_names_out()

array(['status_Married', 'status_Relationship', 'status_Single'],
      dtype=object)

In [75]:
# now just covert it in df

In [76]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out() )

In [77]:
encoder_df

status_Married  status_Relationship  status_Single
0             0.0                  0.0            1.0
1             1.0                  0.0            0.0
2             0.0                  0.0            1.0
3             0.0                  1.0            0.0
4             1.0                  0.0            0.0
5             0.0                  0.0            1.0

In [78]:
# merage it to original data
final_df = pd.concat([df,encoder_df],axis=1)

In [79]:
final_df

status  status_Married  status_Relationship  status_Single
0        Single             0.0                  0.0            1.0
1       Married             1.0                  0.0            0.0
2        Single             0.0                  0.0            1.0
3  Relationship             0.0                  1.0            0.0
4       Married             1.0                  0.0            0.0
5        Single             0.0                  0.0            1.0

In [80]:
# here we covert the categorical data to numerical now >> status coloumn not making any sense we drop it .
# and also drop one column of numerical because two columns are enough to define the status of people who one single 
# AND who one married and who one in relationship 

In [81]:
final_df.drop(['status','status_Married'],axis=1,inplace=True)

In [82]:
final_df # this data use to model training 

status_Relationship  status_Single
0                  0.0            1.0
1                  0.0            0.0
2                  0.0            1.0
3                  1.0            0.0
4                  0.0            0.0
5                  0.0            1.0

In [83]:
# new data >> single---test data
# how would you covert into dummy  variable 
# let see

In [84]:
encoder.transform([['Single']]).toarray()

array([[0., 0., 1.]])

In [85]:

df

status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [86]:
# you can also do same thing using >> get_dummies() >> using pandas

In [91]:
pd.get_dummies(df[['status']],drop_first=True,dtype='int') # here you can also drop one  columns using drop_first

status_Relationship  status_Single
0                    0              1
1                    0              0
2                    0              1
3                    1              0
4                    0              0
5                    0              1

In [97]:
import seaborn as sns
tips=pd.DataFrame(sns.load_dataset("tips"))

In [98]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [108]:
tips.day.value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [113]:
encoder = OneHotEncoder(sparse=False)
encoder

OneHotEncoder(sparse=False)

In [115]:
encoder.fit(tips[['day']])

OneHotEncoder(sparse=False, sparse_output=False)

In [119]:
encoded=encoder.transform(tips[['day']])

In [120]:
encoded

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],


In [121]:
feature_name=encoder.get_feature_names_out()

In [122]:
encoder_df=pd.DataFrame(encoded,columns=feature_name )

In [123]:
encoder_df

day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [124]:
 final_df = pd.concat([tips,encoder_df],axis=1)

In [125]:
 final_df

total_bill   tip     sex smoker   day    time  size  day_Fri  day_Sat  \
0         16.99  1.01  Female     No   Sun  Dinner     2      0.0      0.0   
1         10.34  1.66    Male     No   Sun  Dinner     3      0.0      0.0   
2         21.01  3.50    Male     No   Sun  Dinner     3      0.0      0.0   
3         23.68  3.31    Male     No   Sun  Dinner     2      0.0      0.0   
4         24.59  3.61  Female     No   Sun  Dinner     4      0.0      0.0   
..          ...   ...     ...    ...   ...     ...   ...      ...      ...   
239       29.03  5.92    Male     No   Sat  Dinner     3      0.0      1.0   
240       27.18  2.00  Female    Yes   Sat  Dinner     2      0.0      1.0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2      0.0      1.0   
242       17.82  1.75    Male     No   Sat  Dinner     2      0.0      1.0   
243       18.78  3.00  Female     No  Thur  Dinner     2      0.0      0.0   

     day_Sun  day_Thur  
0        1.0       0.0  
1        1.0       0.0  
2        1.0       0.0  
3        1.0       0.0  
4        1.0       0.0  
..       ...       ...  
239      0.0       0.0  
240      0.0       0.0  
241      0.0       0.0  
242      0.0       0.0  
243      0.0       1.0  

[244 rows x 11 columns]

In [126]:
 final_df.drop(tips[['day']],axis=1,inplace=True)

In [127]:
final_df

total_bill   tip     sex smoker    time  size  day_Fri  day_Sat  day_Sun  \
0         16.99  1.01  Female     No  Dinner     2      0.0      0.0      1.0   
1         10.34  1.66    Male     No  Dinner     3      0.0      0.0      1.0   
2         21.01  3.50    Male     No  Dinner     3      0.0      0.0      1.0   
3         23.68  3.31    Male     No  Dinner     2      0.0      0.0      1.0   
4         24.59  3.61  Female     No  Dinner     4      0.0      0.0      1.0   
..          ...   ...     ...    ...     ...   ...      ...      ...      ...   
239       29.03  5.92    Male     No  Dinner     3      0.0      1.0      0.0   
240       27.18  2.00  Female    Yes  Dinner     2      0.0      1.0      0.0   
241       22.67  2.00    Male    Yes  Dinner     2      0.0      1.0      0.0   
242       17.82  1.75    Male     No  Dinner     2      0.0      1.0      0.0   
243       18.78  3.00  Female     No  Dinner     2      0.0      0.0      0.0   

     day_Thur  
0         0.0  
1         0.0  
2         0.0  
3         0.0  
4         0.0  
..        ...  
239       0.0  
240       0.0  
241       0.0  
242       0.0  
243       1.0  

[244 rows x 10 columns]

In [128]:
# label encoding >> assign unique label to each of categorie

In [129]:
df

status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [130]:
from sklearn.preprocessing import LabelEncoder

In [131]:
label_encoder=LabelEncoder()

In [132]:
label_encoder

LabelEncoder()

In [136]:
label_encoder.fit_transform(df[['status']]) # disadvantage of label encoder 

array([2, 0, 2, 1, 0, 2])

In [138]:
# ordinal encoding 
# high school --1
# graduate --2
# post graduate --3
# phd --4
# how to do it

In [160]:
from sklearn.preprocessing import OrdinalEncoder

In [161]:
df_ordinal=pd.DataFrame({"qualification":['HS','PG','PHD','UG','HS','HS','PG','UG','PG','PHD','HS']})

In [162]:
df_ordinal

qualification
0             HS
1             PG
2            PHD
3             UG
4             HS
5             HS
6             PG
7             UG
8             PG
9            PHD
10            HS

In [163]:
encoder=OrdinalEncoder(categories=[["HS","UG","PG","PHD"]]) #here  give  order

In [164]:
encoder

OrdinalEncoder(categories=[['HS', 'UG', 'PG', 'PHD']])

In [165]:
encoded_df=encoder.fit_transform(df[['qualification']])

In [169]:
encoded_df

array([[0.],
       [2.],
       [3.],
       [1.],
       [0.],
       [0.],
       [2.],
       [1.],
       [2.],
       [3.],
       [0.]])

In [ ]:
# top5/top10>> atleast 70 and 80 percent of the categorical columns captured


In [171]:
df.qualification.value_counts()

qualification
HS     4
PG     3
PHD    2
UG     2
Name: count, dtype: int64

In [172]:
# target guided ordinal encoding
# relation with traget variable 
# A lot of unique categories 
# replace with mean and median

In [174]:
df=pd.DataFrame({'time':['lunch','breakfast ','dinner','lunch','breakfast ','dinner','lunch','breakfast ','dinner'],
               'total_bill':[120,120,40,150,160,130,40,150,160]})

In [175]:
df

time  total_bill
0       lunch         120
1  breakfast          120
2      dinner          40
3       lunch         150
4  breakfast          160
5      dinner         130
6       lunch          40
7  breakfast          150
8      dinner         160

In [177]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()

In [178]:
mean_price

{'breakfast ': 143.33333333333334,
 'dinner': 110.0,
 'lunch': 103.33333333333333}

In [185]:
df['time_target_encoded']=df['time'].map(mean_price)

In [186]:
df

time  total_bill  time_target_encoded
0       lunch         120           103.333333
1  breakfast          120           143.333333
2      dinner          40           110.000000
3       lunch         150           103.333333
4  breakfast          160           143.333333
5      dinner         130           110.000000
6       lunch          40           103.333333
7  breakfast          150           143.333333
8      dinner         160           110.000000

In [ ]:
# new datasets

In [188]:
df=(sns.load_dataset('tips'))

In [189]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [191]:
df.time.value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [192]:
mean_price=df.groupby('time')['total_bill'].mean().to_dict()

In [193]:
mean_price

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [194]:
df['time_target_encoded']=df['time'].map(mean_price)

In [195]:
df['time_target_encoded']

0      20.797159
1      20.797159
2      20.797159
3      20.797159
4      20.797159
         ...    
239    20.797159
240    20.797159
241    20.797159
242    20.797159
243    20.797159
Name: time_target_encoded, Length: 244, dtype: category
Categories (2, float64): [17.168676, 20.797159]

In [196]:
df

total_bill   tip     sex smoker   day    time  size time_target_encoded
0         16.99  1.01  Female     No   Sun  Dinner     2           20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3           20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3           20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2           20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4           20.797159
..          ...   ...     ...    ...   ...     ...   ...                 ...
239       29.03  5.92    Male     No   Sat  Dinner     3           20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2           20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2           20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2           20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2           20.797159

[244 rows x 8 columns]

In [197]:
df.time_target_encoded.value_counts()

time_target_encoded
20.79715909090909     176
17.168676470588235     68
Name: count, dtype: int64